# Generated by Django 4.1.7 on 2023-03-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seminarHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('incharge', models.TextField()),
                ('status', models.CharField(default='Active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status_HoD', models.CharField(max_length=255)),
                ('status_Admin', models.CharField(max_length=255)),
                ('audience', models.IntegerField()),
                ('feedback_HoD', models.TextField(blank=True, null=True)),
                ('feedback_Admin', models.TextField(blank=True, null=True)),
                ('hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HoD', to='app_shms.users')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shms.seminarhall')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shms.users')),
            ],
        ),
    ]
